[theme]
base = "light"
baseFontSize = 14
baseFontWeight = 400
font = "'DM Sans':https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
codeFont = "'DM Mono':https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap"
headingFont = "'DM Sans':https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
showWidgetBorder = true
baseRadius = "6px"
buttonRadius = "6px"

[theme.light]
primaryColor = "#BD2B26"
backgroundColor = "#F9F7F4"
secondaryBackgroundColor = "#EEEDE9"
textColor = "#1B3139"
linkColor = "#BD2B26"
codeBackgroundColor = "#EEEDE9"
codeTextColor = "#1B3139"
borderColor = "#DCE0E2"
dataframeBorderColor = "#DCE0E2"
dataframeHeaderBackgroundColor = "#EEEDE9"

[theme.dark]
primaryColor = "#FF5F46"
backgroundColor = "#0B2026"
secondaryBackgroundColor = "#1B3139"
textColor = "#EEEDE9"
linkColor = "#FF5F46"
codeBackgroundColor = "#1B3139"
codeTextColor = "#EEEDE9"
borderColor = "#303F47"
dataframeBorderColor = "#303F47"
dataframeHeaderBackgroundColor = "#1B3139"
