[theme]
font = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
baseFontSize = 13
headingFontWeights = 600
showWidgetBorder = true
baseRadius = "4px"
buttonRadius = "4px"

[theme.light]
primaryColor = "#2272b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#11171C"
linkColor = "#2272b4"
borderColor = "#CBCBCB"
dataframeBorderColor = "#EBEBEB"
dataframeHeaderBackgroundColor = "#FFFFFF"

[theme.dark]
primaryColor = "#4299E0"
backgroundColor = "#11171C"
secondaryBackgroundColor = "#1f272d"
textColor = "#E8ECF0"
linkColor = "#8ACAFF"
borderColor = "#37444F"
dataframeBorderColor = "#1f272d"
dataframeHeaderBackgroundColor = "#11171C"
